# Number of notes to show when running `codemap show`
default_note_count = 3

# Whether to timestamp notes in a human-readable format
timestamp_format = "iso8601"  # e.g. "2025-07-11T20:15:00Z"

# Enable or disable LLM summaries (can be toggled per-project)
enable_summaries = true

# Optional: Path to custom summary command (for local LLMs)
summary_command = "llama-cli summarize"

# Optional: Project tag for filtering later (future feature)
project_name = "my-project"