[package]
name = "codemap"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0.136"
uuid = { version = "1.3", features = ["v4"] }
chrono = "0.4"
reqwest = { version = "0.11", features = ["json", "blocking"] }
similar = "2.2"
colored = "2.0"
anyhow = "1.0"
rprompt = "2.2.0"
